FROM alpine:3.16.2

# installs public root certs
RUN apk upgrade --update-cache \
    && apk add ca-certificates \
    && rm -rf /var/cache/apk/*

ADD operator-linux-amd64 operator

USER 0

ENTRYPOINT ["/operator"]
