// Code generated by skv2. DO NOT EDIT.

// Package v1alpha1 contains API Schema definitions for the probes.bumblebee.io v1alpha1 API group
// +k8s:deepcopy-gen=package,register
// +groupName=probes.bumblebee.io
package v1alpha1
