// Code generated by protoc-gen-ext. DO NOT EDIT.
// source: github.com/solo-io/bumblebee/api/bumblebee.io/probes/v1alpha1/probe.proto

package v1alpha1

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"strings"

	"github.com/solo-io/protoc-gen-ext/pkg/clone"
	"google.golang.org/protobuf/proto"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = binary.LittleEndian
	_ = bytes.Compare
	_ = strings.Compare
	_ = clone.Cloner(nil)
	_ = proto.Message(nil)
)

// Clone function
func (m *ProbeSpec) Clone() proto.Message {
	var target *ProbeSpec
	if m == nil {
		return target
	}
	target = &ProbeSpec{}

	target.ImageName = m.GetImageName()

	if m.GetNodeSelector() != nil {
		target.NodeSelector = make(map[string]string, len(m.GetNodeSelector()))
		for k, v := range m.GetNodeSelector() {

			target.NodeSelector[k] = v

		}
	}

	target.StatPrefix = m.GetStatPrefix()

	return target
}
