// Code generated by skv2. DO NOT EDIT.

// This file contains generated Deepcopy methods for proto-based Spec and Status fields

package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	"github.com/solo-io/protoc-gen-ext/pkg/clone"
)

// DeepCopyInto for the Probe.Spec
func (in *ProbeSpec) DeepCopyInto(out *ProbeSpec) {
	var p *ProbeSpec
	if h, ok := interface{}(in).(clone.Cloner); ok {
		p = h.Clone().(*ProbeSpec)
	} else {
		p = proto.Clone(in).(*ProbeSpec)
	}
	*out = *p
}
